name: Backfill existing job Issues

on:
  workflow_dispatch:

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y jq curl

      - name: Fetch open issues with label=job
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          mkdir -p jobs
          page=1
          all=()

          while :; do
            RESP=$(curl -sfSL \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              "https://api.github.com/repos/$GH_REPO/issues?state=open&labels=job&per_page=100&page=$page")
            count=$(echo "$RESP" | jq 'length')
            [ "$count" -eq 0 ] && break

            echo "$RESP" | jq -c '.[]' | while read -r issue; do
              BODY=$(echo "$issue" | jq -r '.body')
              NUM=$(echo "$issue"  | jq -r '.number')
              echo "$BODY" | jq . > jobs/_tmp.json
              SLUG=$(jq -r '.slug' jobs/_tmp.json)
              cp jobs/_tmp.json "jobs/${SLUG}.json"
              echo "$NUM" >> jobs/_numbers.txt
            done

            page=$((page+1))
          done

          # build index
          shopt -s nullglob
          FILES=(jobs/*.json)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "[]" > jobs/jobs.json
          else
            jq -s '[ .[] | del(.descriptionHtml) ]' "${FILES[@]}" > jobs/jobs.json
          fi

      - name: Commit backfilled jobs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add jobs/*.json
          git commit -m "Backfill: convert existing job Issues to JSON" || echo "No changes"
          git push

      - name: Close backfilled Issues
        if: hashFiles('jobs/_numbers.txt') != ''
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          while read -r num; do
            curl -sfSL -X PATCH \
              -H "Authorization: Bearer $GH_TOKEN" \
              -H "Accept: application/vnd.github+json" \
              -d '{"state":"closed"}' \
              "https://api.github.com/repos/$GH_REPO/issues/$num"
          done < jobs/_numbers.txt
