name: Convert job Issues to JSON

on:
  issues:
    types: [opened, labeled]

permissions:
  contents: write   # let the workflow commit files
  issues: write     # let the workflow comment/close issues

jobs:
  convert:
    # only run if the issue has label "job"
    if: contains(toJson(github.event.issue.labels), 'job')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Validate that the issue body is JSON
        run: |
          echo '${{ github.event.issue.body }}' | jq . > /dev/null

      - name: Parse body and save jobs/{slug}.json
        shell: bash
        run: |
          set -e
          mkdir -p jobs
          BODY='${{ github.event.issue.body }}'
          # write to temp and parse with jq
          echo "$BODY" | jq . > jobs/_incoming.json
          SLUG=$(jq -r '.slug' jobs/_incoming.json)

          if [ -z "$SLUG" ] || [ "$SLUG" = "null" ]; then
            echo "❌ Missing 'slug' in JSON body"; exit 1
          fi

          cp jobs/_incoming.json "jobs/${SLUG}.json"
          rm jobs/_incoming.json

      - name: Rebuild jobs index (jobs/jobs.json)
        shell: bash
        run: |
          set -e
          shopt -s nullglob
          FILES=(jobs/*.json)
          if [ ${#FILES[@]} -eq 0 ]; then
            echo "[]" > jobs/jobs.json
          else
            # combine all job files; remove descriptionHtml for listing speed
            jq -s '[ .[] | del(.descriptionHtml) ]' "${FILES[@]}" > jobs/jobs.json
          fi

      - name: Commit JSON + index
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add jobs/*.json
          git commit -m "Publish job from Issue #${{ github.event.issue.number }}" || echo "No changes"
          git push

      - name: Comment and close Issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            ✅ Thanks! This internship has been published to the job board.
            File: /jobs/${{ fromJson(github.event.issue.body).slug }}.json
            Index
