name: Convert job Issues to JSON

on:
  issues:
    types: [opened, labeled]

permissions:
  contents: write
  issues: write

jobs:
  convert:
    if: contains(toJson(github.event.issue.labels), 'job')
    runs-on: ubuntu-latest
    steps:
      # (leave the rest exactly as you have it)

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Skip if already published
        id: skipcheck
        shell: bash
        run: |
          BODY='${{ github.event.issue.body }}'
          echo "$BODY" | jq . > /dev/null
          SLUG=$(echo "$BODY" | jq -r '.slug')
          if [ -f "jobs/${SLUG}.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Validate that the issue body is JSON
        run: |
          echo '${{ github.event.issue.body }}' | jq . > /dev/null

           - name: Parse body and save jobs/{slug}.json
        if: steps.skipcheck.outputs.exists == 'false'
        run: |
          # same content…

      - name: Rebuild jobs index (jobs/jobs.json)
        if: steps.skipcheck.outputs.exists == 'false'
        run: |
          # same content…

      - name: Commit JSON + index
        if: steps.skipcheck.outputs.exists == 'false'
        run: |
          # same content…

      - name: Comment and close Issue
        if: steps.skipcheck.outputs.exists == 'false'
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: |
            ✅ Thanks! This internship has been published…
